name: silesian_prototype
description: "A Flutter project that recreates a screen for an application dedicated to the Silesian region."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  video_player: ^2.9.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - lib/assets/images/
    - lib/assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400        
        - asset: lib/assets/fonts/Roboto-Light.ttf
          weight: 300
